### ISSUE TITLE
LoRA/loralib/layers.py line 59 & 60

### ISSUE THREAD

**Issue by mhmdsabry** [microsoft/LoRA#42]
Hi,
Really impressive work, thank you!

**Should A & B initialisation be the opposite?**

![Firefox_Screenshot_2022-12-22T10-42-32 475Z](https://user-images.githubusercontent.com/19279413/209118591-aed9e616-134c-4026-b317-c39ab89ba3ee.png)

**Comment by edwardjhu** [comment]
Thanks Mohammed,

Yes, you are right about this piece of code being slightly different from what we described in the paper (and from the comment in line 58).

However, I don't think it should make a difference in practice since we still get gradient updates for both layers. So, I'm inclined to keep it as it is for reproducibility and change the comment to reflect what we actually do. Do you see any problems with how it's done right now, or are you just pointing out this inconsistency?

**Comment by mhmdsabry** [comment]
No, Just pointing out inconsistency. Thanks for your response.
